In [1]:
import numpy as np

In [7]:
#операции над матрицами
#1
simple_matrix_a = np.array([
    [1, 2, 4],
    [7, 5, -2],
    [-2, 1, 3]
])

simple_matrix_b = np.array([
    [-1, 0, 3],
    [2, -6, 1],
    [-7, 1, 5]
])

simple_matrix_c = np.array([
    [-2, 3],
    [4, 0],
    [7, -1]
])

def calculate(matr1, matr2, matr3):
    print(f'A + B = \n{matr1 + matr2}')
    print(f'B - A = \n{matr2 - matr1}')
    print(f'A * C = \n{matr1 @ matr3}')
    print(f'A * B * C = \n{matr1 @ matr2 @ matr3}')

calculate(simple_matrix_a, simple_matrix_b, simple_matrix_c)

A + B = 
[[ 0  2  7]
 [ 9 -1 -1]
 [-9  2  8]]
B - A = 
[[ -2  -2  -1]
 [ -5 -11   3]
 [ -5   0   2]]
A * C = 
[[34 -1]
 [-8 23]
 [29 -9]]
A * B * C = 
[[ 193 -100]
 [ -50   35]
 [  92  -61]]


In [11]:
#2
simple_matrix_a = np.array([
    [0, 3, 4],
    [-7, 1, -2],
    [2, -1, 3]
])

simple_matrix_b = np.array([
    [1, 2, 4],
    [7, 0, -2],
    [-3, -2, 5]
])

simple_matrix_c = np.array([
    [-3, 2],
    [0, 4],
    [-1, 7]
])

def calculate(matr1, matr2, matr3):
    print(f'A + B = \n{matr1 + matr2}')
    print(f'B - A = \n{matr2 - matr1}')
    print(f'A * C = \n{matr1 @ matr3}')
    print(f'A * B * C = \n{matr1 @ matr2 @ matr3}')

calculate(simple_matrix_a, simple_matrix_b, simple_matrix_c)

A + B = 
[[ 1  5  8]
 [ 0  1 -4]
 [-1 -3  8]]
B - A = 
[[ 1 -1  0]
 [14 -1  0]
 [-5 -1  2]]
A * C = 
[[ -4  40]
 [ 23 -24]
 [ -9  21]]
A * B * C = 
[[ -41   84]
 [  22 -308]
 [  17  139]]


In [12]:
#3
simple_matrix_a = np.array([
    [5, 2, 9],
    [7, 0, -2],
    [-2, 1, 6]
])

simple_matrix_b = np.array([
    [1, -2, 1],
    [7, 5, -2],
    [-2, 8, 3]
])

simple_matrix_c = np.array([
    [-2, 3],
    [4, 5],
    [0, -1]
])

def calculate(matr1, matr2, matr3):
    print(f'A + B = \n{matr1 + matr2}')
    print(f'B - A = \n{matr2 - matr1}')
    print(f'A * C = \n{matr1 @ matr3}')
    print(f'A * B * C = \n{matr1 @ matr2 @ matr3}')

calculate(simple_matrix_a, simple_matrix_b, simple_matrix_c)

A + B = 
[[ 6  0 10]
 [14  5 -4]
 [-4  9  9]]
B - A = 
[[-4 -4 -8]
 [ 0  5  0]
 [ 0  7 -3]]
A * C = 
[[ -2  16]
 [-14  23]
 [  8  -7]]
A * B * C = 
[[ 286  335]
 [-142 -118]
 [ 242  250]]


In [13]:
#4
simple_matrix_a = np.array([
    [1, -2, 8],
    [7, 5, -2],
    [-2, 3, 0]
])

simple_matrix_b = np.array([
    [0, 2, 4],
    [1, -3, -2],
    [-2, 1, 3]
])

simple_matrix_c = np.array([
    [0, 3],
    [5, -4],
    [7, -1]
])

def calculate(matr1, matr2, matr3):
    print(f'A + B = \n{matr1 + matr2}')
    print(f'B - A = \n{matr2 - matr1}')
    print(f'A * C = \n{matr1 @ matr3}')
    print(f'A * B * C = \n{matr1 @ matr2 @ matr3}')

calculate(simple_matrix_a, simple_matrix_b, simple_matrix_c)

A + B = 
[[ 1  0 12]
 [ 8  2 -4]
 [-4  4  3]]
B - A = 
[[-1  4 -4]
 [-6 -8  0]
 [ 0 -2  3]]
A * C = 
[[ 46   3]
 [ 11   3]
 [ 15 -18]]
A * B * C = 
[[ 304 -150]
 [  69   27]
 [-163   75]]


In [14]:
#5
simple_matrix_a = np.array([
    [9, 2, 4],
    [7, 5, -5],
    [6, -2, 3]
])

simple_matrix_b = np.array([
    [8, 2, 4],
    [0, 1, -3],
    [-2, 1, 6]
])

simple_matrix_c = np.array([
    [-2, 0],
    [4, 8],
    [1, -1]
])

def calculate(matr1, matr2, matr3):
    print(f'A + B = \n{matr1 + matr2}')
    print(f'B - A = \n{matr2 - matr1}')
    print(f'A * C = \n{matr1 @ matr3}')
    print(f'A * B * C = \n{matr1 @ matr2 @ matr3}')

calculate(simple_matrix_a, simple_matrix_b, simple_matrix_c)

A + B = 
[[17  4  8]
 [ 7  6 -8]
 [ 4 -1  9]]
B - A = 
[[-1  0  0]
 [-7 -4  2]
 [-8  3  3]]
A * C = 
[[ -6  12]
 [  1  45]
 [-17 -19]]
A * B * C = 
[[ 22 138]
 [-93 129]
 [ 16  56]]


In [8]:
#поиск обратной матрицы
#1
simple_matrix_a = np.array([
    [1, 2, 4],
    [7, 5, -2],
    [-2, 1, 3]
])

def calculate_inv(matr1):
    print(f'Обратная матрица к матрице А:\n{np.linalg.inv(matr1)}')

calculate_inv(simple_matrix_a)

Обратная матрица к матрице А:
[[ 0.33333333 -0.03921569 -0.47058824]
 [-0.33333333  0.21568627  0.58823529]
 [ 0.33333333 -0.09803922 -0.17647059]]


In [9]:
#2
simple_matrix_a = np.array([
    [5, 2, 9],
    [7, 0, -2],
    [-2, 1, 6]
])

def calculate_inv(matr1):
    print(f'Обратная матрица к матрице А:\n{np.linalg.inv(matr1)}')

calculate_inv(simple_matrix_a)

Обратная матрица к матрице А:
[[ -0.66666667   1.           1.33333333]
 [ 12.66666667 -16.         -24.33333333]
 [ -2.33333333   3.           4.66666667]]


In [10]:
#3
simple_matrix_a = np.array([
    [9, 2, 4],
    [7, 5, -5],
    [6, -2, 3]
])

def calculate_inv(matr1):
    print(f'Обратная матрица к матрице А:\n{np.linalg.inv(matr1)}')

calculate_inv(simple_matrix_a)

Обратная матрица к матрице А:
[[-0.02145923  0.06008584  0.12875536]
 [ 0.21888412 -0.01287554 -0.31330472]
 [ 0.1888412  -0.12875536 -0.13304721]]
